### ISSUE TITLE
Can't edit the google docs with whackamole enabled

### ISSUE THREAD

**Issue by jsramraj** [laffra/whackamole#3]
I started using this for a while and find it useful than using the Ad-Blocker. Lot of sites (particularly the news websites) doesn't allow to read content with Ad-Blocker. But they don't warn me if I use this tool.

But I found one problem with this tool. Ever since I installed this extension, I couldn't edit the Google Docs, the content is disabled completely. Sometimes, I even couldn't view the files, it says **unknown error occurred, please reload.**. 

I use google docs a lot, the only way I could make them work is by disabling the whakamole.

**Comment by laffra** [comment]
You can disable Whackamole for selected sites. I disabled it for Google Docs, Gmail, Sheets, etc. To enable/disable given sites, click the red cross icon in the toolbar when visiting the site.

**Comment by jsramraj** [comment]
Okay, I'll also do that. Closing this issue for now.
